name: Tailscale (for advanced users)

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: buildjet-16vcpu-ubuntu-2204

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Set up Tailscale
        run: curl -sSf https://sshx.io/get | sh -s run
      - name: Set up 
        run: sleep inf
            -vnc :0,audiodev=audiodev0 \
            -device virtio-net-pci,netdev=net0 \
            -bios /usr/share/ovmf/OVMF.fd \
            -netdev user,id=net0,hostfwd=tcp::3389-:3389
