name: Tailscale (for advance user)

on: 
  workflow_dispatch:
 
 
jobs:
  build:
    timeout-minutes: 1440
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:

    - name: Free Disk Space (Ubuntu)
 			run: sleep 600
   
